name: Process README Updates

on:
  push:
    paths:
      - "README.md"   # Only trigger workflow when README file change
  pull_request:
    paths:
      - "README.md"

jobs:
  check-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check README Formatting
        run: |
          if [[ ! -s README.md ]]; then
            echo "Error: README.md is empty!"
            exit 1
          fi
          echo "README.md exists and is not empty. ✅"

      - name: Generate README Preview (Optional)
        run: |
          echo "Generating README preview..."
          cat README.md

  notify-success:
    needs: check-readme
    runs-on: ubuntu-latest
    steps:
      - name: Notify success
        run: echo "README.md processed successfully! 🚀"
